"use client"

import * as React from "react"
import { PageHeader } from "@/components/ui/page-header"
import { StatCard } from "@/components/ui/stat-card"
import {
  CheckCircle2, AlertCircle, Clock, XCircle, Play, Loader2,
  TrendingUp, TrendingDown, Minus, Timer
} from "lucide-react"

type ChecklistStatus = "COMPLETE" | "PENDING" | "EXCEPTION" | "NOT_APPLICABLE"

interface CloseResult {
  period: string
  checklist: { id: string; label: string; status: ChecklistStatus; detail?: string; automatedBy?: string }[]
  autoGeneratedEntries: { type: string; amount: number; description: string }[]
  fluxAnalysis: { line: string; variance: number; pct: number; explanation: string }[]
  exceptionsQueue: { id: string; description: string; urgency: "HIGH" | "MEDIUM" | "LOW" }[]
  totalHumanMinutes: number
}

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n)
}

function StatusIcon({ status }: { status: ChecklistStatus }) {
  const map = {
    COMPLETE:       <CheckCircle2 className="h-4 w-4 text-emerald-500" />,
    PENDING:        <Clock className="h-4 w-4 text-amber-500" />,
    EXCEPTION:      <AlertCircle className="h-4 w-4 text-red-500" />,
    NOT_APPLICABLE: <XCircle className="h-4 w-4 text-muted-foreground/30" />,
  }
  return map[status]
}

const STATUS_BADGE: Record<ChecklistStatus, string> = {
  COMPLETE:       "badge-success",
  PENDING:        "badge-warning",
  EXCEPTION:      "badge-error",
  NOT_APPLICABLE: "badge-neutral",
}

const STATUS_LABEL: Record<ChecklistStatus, string> = {
  COMPLETE: "Complete", PENDING: "Pending", EXCEPTION: "Exception", NOT_APPLICABLE: "N/A",
}

function StatusBadge({ status }: { status: ChecklistStatus }) {
  return <span className={STATUS_BADGE[status]}>{STATUS_LABEL[status]}</span>
}

const URGENCY_BADGE: Record<"HIGH" | "MEDIUM" | "LOW", string> = {
  HIGH:   "badge-error",
  MEDIUM: "badge-warning",
  LOW:    "badge-neutral",
}

function UrgencyBadge({ urgency }: { urgency: "HIGH" | "MEDIUM" | "LOW" }) {
  return <span className={URGENCY_BADGE[urgency]}>{urgency}</span>
}

export default function ClosePage() {
  const [result, setResult] = React.useState<CloseResult | null>(null)
  const [loading, setLoading] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)

  async function runClose() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch("/api/agents/close", { method: "POST" })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? "Close agent failed")
      setResult(json)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const completeCount = result?.checklist.filter((c) => c.status === "COMPLETE").length ?? 0
  const totalCount = result?.checklist.filter((c) => c.status !== "NOT_APPLICABLE").length ?? 0
  const progressPct = totalCount > 0 ? (completeCount / totalCount) * 100 : 0

  return (
    <div className="space-y-8">
      <PageHeader
        title="Month-End Close"
        description="AI-automated close checklist. Run the Close Agent to generate journal entries, flux analysis, and exception queue."
        right={
          <button
            onClick={runClose}
            disabled={loading}
            className="btn-primary disabled:opacity-60 disabled:translate-y-0 disabled:cursor-not-allowed"
          >
            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}
            {loading ? "Running close…" : "Run Close Agent"}
          </button>
        }
      />

      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 dark:bg-red-950/20 p-4 flex items-center gap-3">
          <AlertCircle className="h-4 w-4 text-red-500 shrink-0" />
          <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
        </div>
      )}

      {!result && !loading && (
        <div className="card-default p-12 flex flex-col items-center text-center gap-6">
          <div className="h-14 w-14 rounded-2xl bg-primary/8 border border-primary/20 flex items-center justify-center">
            <Timer className="h-7 w-7 text-primary" />
          </div>
          <div>
            <p className="font-display font-semibold text-lg">Ready to close</p>
            <p className="text-sm text-muted-foreground mt-1.5 max-w-sm leading-relaxed">
              Click <strong>Run Close Agent</strong> to execute the automated close checklist, generate journal entries, and produce flux analysis for the current period.
            </p>
          </div>
          <div className="flex items-center gap-8">
            <div className="text-center">
              <p className="font-display font-bold text-3xl num">~2h</p>
              <p className="text-xs text-muted-foreground mt-1">Estimated human time</p>
            </div>
            <div className="h-10 border-l border-border" />
            <div className="text-center">
              <p className="font-display font-bold text-3xl num text-muted-foreground line-through">3 wks</p>
              <p className="text-xs text-muted-foreground mt-1">Traditional close time</p>
            </div>
          </div>
        </div>
      )}

      {result && (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <StatCard label="Period" value={result.period} />
            <StatCard
              label="Checklist Progress"
              value={`${completeCount} / ${totalCount}`}
              sub={`${progressPct.toFixed(0)}% complete`}
              trend={progressPct === 100 ? "up" : "neutral"}
            />
            <StatCard
              label="Exceptions"
              value={result.exceptionsQueue.length}
              sub={result.exceptionsQueue.length > 0 ? "Require human review" : "None — clean close"}
              trend={result.exceptionsQueue.length > 0 ? "down" : "up"}
            />
            <StatCard
              label="Human Time Required"
              value={`${result.totalHumanMinutes} min`}
              sub="AI handled the rest"
              trend="up"
            />
          </div>

          {totalCount > 0 && (
            <div className="flex items-center gap-3">
              <div className="flex-1 h-2 rounded-full bg-muted overflow-hidden">
                <div
                  className="h-full rounded-full bg-emerald-500 transition-all duration-700"
                  style={{ width: `${progressPct}%` }}
                />
              </div>
              <span className="text-xs text-muted-foreground shrink-0">{progressPct.toFixed(0)}%</span>
            </div>
          )}

          <div className="card-default overflow-hidden">
            <div className="px-5 py-4 border-b">
              <p className="text-sm font-semibold">Close Checklist</p>
              <p className="text-xs text-muted-foreground mt-0.5">Automated by Ryzha agents — exceptions surface for human review only</p>
            </div>
            <div className="divide-y">
              {result.checklist.map((item) => (
                <div key={item.id} className="flex items-center gap-4 px-5 py-3.5 table-row-hover">
                  <StatusIcon status={item.status} />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">{item.label}</p>
                    {item.detail && <p className="text-xs text-muted-foreground mt-0.5">{item.detail}</p>}
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    {item.automatedBy && (
                      <span className="text-[10px] text-muted-foreground/60 hidden sm:block">{item.automatedBy}</span>
                    )}
                    <StatusBadge status={item.status} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {result.exceptionsQueue.length > 0 && (
            <div className="rounded-xl border border-red-200 dark:border-red-900/50 bg-red-50/50 dark:bg-red-950/10 overflow-hidden">
              <div className="px-5 py-4 border-b border-red-200 dark:border-red-900/50">
                <p className="text-sm font-semibold text-red-700 dark:text-red-400">Exceptions Queue — Human Review Required</p>
                <p className="text-xs text-muted-foreground mt-0.5">These items require your input before close can complete</p>
              </div>
              <div className="divide-y divide-red-100 dark:divide-red-900/30">
                {result.exceptionsQueue.map((ex) => (
                  <div key={ex.id} className="flex items-center gap-4 px-5 py-3.5">
                    <AlertCircle className="h-4 w-4 text-red-500 shrink-0" />
                    <p className="flex-1 text-sm">{ex.description}</p>
                    <UrgencyBadge urgency={ex.urgency} />
                  </div>
                ))}
              </div>
            </div>
          )}

          {result.autoGeneratedEntries.length > 0 && (
            <div className="card-default overflow-hidden">
              <div className="px-5 py-4 border-b">
                <p className="text-sm font-semibold">Auto-Generated Journal Entries</p>
                <p className="text-xs text-muted-foreground mt-0.5">Posted to your accounting system automatically by the Close Agent</p>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b bg-muted/20">
                    <th className="text-left px-5 py-3 text-[11px] uppercase tracking-wider font-medium text-muted-foreground">Type</th>
                    <th className="text-left px-5 py-3 text-[11px] uppercase tracking-wider font-medium text-muted-foreground">Description</th>
                    <th className="text-right px-5 py-3 text-[11px] uppercase tracking-wider font-medium text-muted-foreground">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {result.autoGeneratedEntries.map((e, i) => (
                    <tr key={i} className="table-row-hover">
                      <td className="px-5 py-3">
                        <span className="badge-active text-[10px] uppercase tracking-wide">{e.type}</span>
                      </td>
                      <td className="px-5 py-3 text-muted-foreground text-sm">{e.description}</td>
                      <td className="px-5 py-3 text-right num">{formatCurrency(e.amount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {result.fluxAnalysis.length > 0 && (
            <div className="card-default p-6 space-y-4">
              <div>
                <p className="text-sm font-semibold">Flux Analysis</p>
                <p className="text-xs text-muted-foreground mt-0.5">AI-generated variance commentary vs prior month</p>
              </div>
              <div className="space-y-3">
                {result.fluxAnalysis.map((f) => {
                  const positive = f.variance >= 0
                  return (
                    <div key={f.line} className="flex gap-4 p-4 rounded-xl bg-muted/30 border">
                      <div className="shrink-0 mt-0.5">
                        {Math.abs(f.pct) < 5
                          ? <Minus className="h-4 w-4 text-muted-foreground" />
                          : positive
                          ? <TrendingUp className="h-4 w-4 text-emerald-500" />
                          : <TrendingDown className="h-4 w-4 text-red-500" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-3 mb-1 flex-wrap">
                          <p className="text-sm font-semibold">{f.line}</p>
                          <span className={`text-xs font-medium num ${positive ? "num-pos" : "num-neg"}`}>
                            {positive ? "+" : ""}{f.pct.toFixed(1)}% ({formatCurrency(Math.abs(f.variance))})
                          </span>
                        </div>
                        <p className="text-sm text-muted-foreground leading-relaxed">{f.explanation}</p>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}
