"use client"

import * as React from "react"
import { TrendingUp, TrendingDown, BarChart2, AlertCircle, Sparkles, Loader2, ChevronDown, ChevronUp } from "lucide-react"

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n)
}

interface BoardReport {
  period: string
  narrative: string
  keyMetrics: {
    mrr: number
    arr: number
    mrrGrowth: number
    burnRate: number
    runway: number
    netBurn: number
    revenueThisMonth: number
    expensesThisMonth: number
    newSubscriptions: number
    cancelledSubscriptions: number
    anomaliesDetected: number
    pendingApprovals: number
  }
  riskFlags: { severity: "HIGH" | "MEDIUM" | "LOW"; message: string }[]
  generatedAt: string
}

function RiskBadge({ severity }: { severity: "HIGH" | "MEDIUM" | "LOW" }) {
  const map = {
    HIGH: "bg-red-50 text-red-600 dark:bg-red-950/40 dark:text-red-400",
    MEDIUM: "bg-yellow-50 text-yellow-700 dark:bg-yellow-950/40 dark:text-yellow-400",
    LOW: "bg-muted text-muted-foreground",
  }
  return <span className={`text-xs font-medium px-2 py-0.5 rounded-full shrink-0 ${map[severity]}`}>{severity}</span>
}

function Narrative({ text }: { text: string }) {
  const paragraphs = text.split("\n\n").filter(Boolean)
  return (
    <div className="space-y-3 text-sm leading-relaxed text-foreground/80">
      {paragraphs.map((p, i) => {
        const parts = p.split(/(\*\*[^*]+\*\*)/g)
        return (
          <p key={i}>
            {parts.map((part, j) =>
              part.startsWith("**") && part.endsWith("**")
                ? <strong key={j} className="text-foreground font-semibold">{part.slice(2, -2)}</strong>
                : part
            )}
          </p>
        )
      })}
    </div>
  )
}

function MetricPair({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="space-y-0.5">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-lg font-bold tabular-nums">{value}</p>
      {sub && <p className="text-[11px] text-muted-foreground">{sub}</p>}
    </div>
  )
}

export default function ReportsPage() {
  const [report, setReport] = React.useState<BoardReport | null>(null)
  const [loading, setLoading] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)
  const [expanded, setExpanded] = React.useState(false)

  async function generate() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch("/api/agents/board-report", { method: "POST" })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? "Failed to generate report")
      setReport(json)
      setExpanded(true)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold">Reports</h2>
          <p className="text-muted-foreground text-sm mt-1">
            Real-time financial intelligence - generated by AI from your Unified Financial Event Stream.
          </p>
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 disabled:opacity-60 transition-colors shrink-0"
        >
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4" />
          )}
          {loading ? "Generating…" : "Generate Board Report"}
        </button>
      </div>

      {error && (
        <div className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 dark:bg-red-950/20 dark:border-red-900/40 p-4">
          <AlertCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
          <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
        </div>
      )}

      {!report && !loading && (
        <div className="rounded-xl border bg-card flex flex-col items-center justify-center py-20 gap-4 text-center">
          <BarChart2 className="h-10 w-10 text-muted-foreground/40" />
          <div>
            <p className="font-semibold">No report generated yet</p>
            <p className="text-sm text-muted-foreground mt-1 max-w-sm">
              Click "Generate Board Report" to have the AI analyse your financial data and produce a board-ready narrative.
            </p>
          </div>
        </div>
      )}

      {loading && (
        <div className="rounded-xl border bg-card flex flex-col items-center justify-center py-20 gap-4">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <div className="text-center">
            <p className="font-semibold">Analysing your financial data…</p>
            <p className="text-sm text-muted-foreground mt-1">Ryzha is reading your event stream, running metrics, and drafting the narrative.</p>
          </div>
        </div>
      )}

      {report && (
        <>
          <div className="rounded-xl border bg-card overflow-hidden">
            <div
              className="flex items-center justify-between p-5 cursor-pointer hover:bg-muted/30 transition-colors"
              onClick={() => setExpanded((v) => !v)}
            >
              <div className="flex items-center gap-3">
                <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Sparkles className="h-4 w-4 text-primary" />
                </div>
                <div>
                  <p className="font-semibold">AI Board Narrative - {report.period}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Generated {new Date(report.generatedAt).toLocaleTimeString()} · powered by Ryzha Intelligence
                  </p>
                </div>
              </div>
              {expanded ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
            </div>

            {expanded && (
              <div className="border-t px-5 py-5 space-y-5">
                <Narrative text={report.narrative} />

                {report.riskFlags.length > 0 && (
                  <div className="rounded-lg border bg-muted/30 p-4 space-y-2">
                    <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Risk Flags</p>
                    {report.riskFlags.map((f, i) => (
                      <div key={i} className="flex items-start gap-2.5">
                        <RiskBadge severity={f.severity} />
                        <p className="text-sm">{f.message}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-3">Key Metrics - {report.period}</p>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="MRR" value={formatCurrency(report.keyMetrics.mrr)} sub={`${report.keyMetrics.mrrGrowth >= 0 ? "+" : ""}${report.keyMetrics.mrrGrowth.toFixed(1)}% MoM`} />
              </div>
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="ARR" value={formatCurrency(report.keyMetrics.arr)} sub="MRR × 12" />
              </div>
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="Monthly Burn" value={formatCurrency(report.keyMetrics.burnRate)} />
              </div>
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="Net Burn" value={formatCurrency(report.keyMetrics.netBurn)} sub={report.keyMetrics.netBurn > 0 ? "Cash out > cash in" : "Revenue exceeds cost"} />
              </div>
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="New Subs" value={String(report.keyMetrics.newSubscriptions)} />
              </div>
              <div className="rounded-xl border bg-card p-4">
                <MetricPair label="Churned" value={String(report.keyMetrics.cancelledSubscriptions)} />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="rounded-xl border bg-card p-5 space-y-3">
              <p className="font-semibold">Revenue vs Expenses</p>
              <div className="space-y-3">
                <div>
                  <div className="flex justify-between text-xs text-muted-foreground mb-1.5">
                    <span>Revenue</span>
                    <span className="font-medium text-foreground">{formatCurrency(report.keyMetrics.revenueThisMonth)}</span>
                  </div>
                  <div className="h-2 rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full bg-emerald-500"
                      style={{ width: `${Math.min(100, (report.keyMetrics.revenueThisMonth / Math.max(report.keyMetrics.burnRate, 1)) * 100)}%` }}
                    />
                  </div>
                </div>
                <div>
                  <div className="flex justify-between text-xs text-muted-foreground mb-1.5">
                    <span>Expenses</span>
                    <span className="font-medium text-foreground">{formatCurrency(report.keyMetrics.expensesThisMonth)}</span>
                  </div>
                  <div className="h-2 rounded-full bg-muted overflow-hidden">
                    <div className="h-full rounded-full bg-red-400" style={{ width: "100%" }} />
                  </div>
                </div>
              </div>
              <div className="pt-2 border-t flex justify-between text-sm">
                <span className="text-muted-foreground">Net Income</span>
                <span className={`font-semibold tabular-nums ${report.keyMetrics.revenueThisMonth >= report.keyMetrics.expensesThisMonth ? "text-emerald-600" : "text-red-500"}`}>
                  {formatCurrency(report.keyMetrics.revenueThisMonth - report.keyMetrics.expensesThisMonth)}
                </span>
              </div>
            </div>

            <div className="rounded-xl border bg-card p-5 space-y-3">
              <p className="font-semibold">Operational Status</p>
              <div className="divide-y">
                {[
                  { label: "Anomalies detected", value: report.keyMetrics.anomaliesDetected, highlight: report.keyMetrics.anomaliesDetected > 0 },
                  { label: "Pending approvals", value: report.keyMetrics.pendingApprovals, highlight: report.keyMetrics.pendingApprovals > 0 },
                  { label: "New subscriptions", value: report.keyMetrics.newSubscriptions, highlight: false },
                  { label: "Churned subscriptions", value: report.keyMetrics.cancelledSubscriptions, highlight: report.keyMetrics.cancelledSubscriptions > 0 },
                ].map((item) => (
                  <div key={item.label} className="flex items-center justify-between py-2.5 first:pt-0 last:pb-0">
                    <span className="text-sm text-muted-foreground">{item.label}</span>
                    <span className={`text-sm font-semibold tabular-nums ${item.highlight ? "text-amber-600" : ""}`}>
                      {item.value}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-muted bg-muted/20 p-4 flex items-start gap-3">
            <AlertCircle className="h-4 w-4 text-muted-foreground shrink-0 mt-0.5" />
            <p className="text-xs text-muted-foreground">
              This report is generated from financial events ingested into Ryzha's Unified Financial Event Stream.
              Accuracy improves as more platforms are connected and Revenue, Cash, and AP agents have run.
              Last generated: {new Date(report.generatedAt).toLocaleString()}
            </p>
          </div>
        </>
      )}
    </div>
  )
}
